config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :itenaries
  resources :solutions
  resources :questions
  resources :quizzes
  resources :information
  resources :tours
  resources :estimates
  resources :researches
  resources :feedbacks
  devise_for :admins
  resources :words
  resources :communities
  resources :years
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { registrations: "registrations" }
  resources :stories
  resources :targets
  root "welcome#welcome" 
  
  get 'docipedias/', to: 'docipedias#index', as: 'index'

  resources :conversations do
   resources :messages
  end

  


  get 'home/' => 'home#home', as: 'home'
  get 'accountsettings/' => 'home#accountsettings', as: 'accountsettings'
  get 'systemaccess/' => 'home#systemaccess', as: 'systemaccess'
  get 'targetreport/' => 'home#targetreport', as: 'targetreport'
  get 'yearreport/' => 'home#yearreport', as: 'yearreport'
  get 'expensereport/' => 'home#expensereport', as: 'expense'
  get 'bookmark/' => 'home#bookmark', as: 'bookmark'
  get 'custom/' => 'home#custom', as: 'custom'
  get 'bucket_list/' => 'home#bucket_list', as: 'bucket_list'
  get 'set_bucket_list/' => 'home#set_bucket_list', as: 'set_bucket_list'
  get 'destinations' => 'home#destinations', as: 'destinations'
  get 'news' => 'home#news', as: 'news'
  resources :visits

  
 
  

  get 'groupnew/' => 'targets#groupnew', as: 'groupnew'
  get 'groupindex/' => 'targets#groupindex', as: 'groupindex'
  get 'othernew/' => 'itenaries#othernew', as: 'othernew'

   get 'launch/' => 'quizzes#launch', as: 'launch'
   get 'aroundme/' => 'topics#aroundme', as: 'aroundme'
   get 'technology/' => 'topics#technology', as: 'technology'
   get 'travel/' => 'topics#travel', as: 'travel'
   get 'food/' => 'topics#food', as: 'food'
   get 'career/' => 'topics#career', as: 'career'
   get 'examination/' => 'topics#examination', as: 'examination'

 

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/target.rb
class Target < ApplicationRecord
	has_many :tasks, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :tasks,
	                               allow_destroy: :true, 
	                               reject_if: lambda{ |attrs| attrs['name'].blank? }

	mount_uploader :doc, DocumentUploader

	validates_presence_of :name, :description, :begin, :end


end

app/controllers/targets_controller.rb
    class TargetsController < ApplicationController
      before_action :authenticate_user!
      before_action :set_target, only: [:show, :edit, :update, :destroy]
       layout :determine_layout

      # GET /targets
      # GET /targets.json
      def index
        @personal_targets = (Target.where(user_id: current_user.id)).page(params[:page])

        @completed_targets = (Target.where(user_id: current_user.id)).page(params[:page])

                  @stale_personal_targets = (Target.where(user_id: current_user.id) && Target.where(lead: nil))

                   @p = []
                   @h = []
                   @jj = []


                   @stale_personal_targets.each do |target|

          
         
                        target.tasks.each do |task|


                          
             
                           q = task.dateofcompletion
                           m = task.updated_at.to_date
                           
               

                            if (@flag = ((q - m).to_i >= 3) && task.progress != 100)
                              if (task.owner == current_user.id)
                                 
                                 @p << task.target_id
                                 @h << task.name
                                 @jj = @p.zip(@h)
                              end
                             end 
                        end
                      
                  end
        
      end



      # GET /targets/1
      # GET /targets/1.json
      def show
             @v = 0
             @n = 0
         @target.tasks.each do |g|
         @count = 0

         @w = 0
         
         y = g.updated_at.to_date
         c = Date.today
         if(@r = ((c-y).to_i >=3))
         @count =+1
         end
         if g.progress.between?(0,24)
          @v = @v+1 
         end
         if g.progress.between?(75,100)
          @n = @n+1
         end

         
       end
       @g = (@target.tasks.count)*100
       @j =  @target.tasks.sum(:progress)
         @x = @g - @j





      end
      # GET /targets/new
      def new
        @target = Target.new

      end

      def groupnew
        @target = Target.new
      end

     def groupindex
        @group_targets = (Target.where(":user_id = ANY(member)", user_id: current_user.id )).page(params[:page])

        @groupp_targets = (Target.where(":user_id = ANY(member)", user_id: current_user.id )).page(params[:page])
        

          @stale_group_targets = (Target.where(":user_id = ANY(member)", user_id: current_user.id ))

                   @e = []
                   @u = []
                   @kk = []


                   @stale_group_targets.each do |target|

          
         
                        target.tasks.each do |task|


                          
             
                             q = task.dateofcompletion
                           m = task.updated_at.to_date
                           
               

                            if (@flag = ((q - m).to_i >= 3) && task.progress != 100)

                               if (task.owner == current_user.id)  
                                 @e << task.target_id
                                 @u << task.name
                                 @kk = @e.zip(@u)
                                end
                             end 
                        end
                        
                  end
         
      end


      # GET /targets/1/edit
      def edit
      end

      # POST /targets
      # POST /targets.json
      def create
        @target = Target.new(target_params.merge(user_id: current_user.id))
        
        respond_to do |format|
          if @target.save
            format.html { redirect_to @target, notice: 'Target was successfully created.' }
            format.json { render :show, status: :created, location: @target }
          else
            format.html { render :new }
            format.json { render json: @target.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /targets/1
      # PATCH/PUT /targets/1.json
      def update
        respond_to do |format|
          if @target.update(target_params)
            format.html { redirect_to @target, notice: 'Target was successfully updated.' }
            format.json { render :show, status: :ok, location: @target }
          else
            format.html { render :edit }
            format.json { render json: @target.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /targets/1
      # DELETE /targets/1.json
      def destroy
        @target.destroy
        respond_to do |format|
          format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_target
          @target = Target.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def target_params
          params.require(:target).permit(:name, :description, :begin, :end, :doc, {:member => []}, :lead, tasks_attributes: [:id, :name, :point, :owner, :progress, :dateofcompletion, :_destroy])
        end
        def determine_layout

        case current_user.colour

        when "orange"
        "myhomefour"

        when "black"
        "myhomethree"

        when "green"
        "myhometwo"

        else
        "myhome"
      end
    end
    end

app/helpers/targets_helper.rb
module TargetsHelper
	
end

app/views/targets/groupindex.html.erb
<div class="container"id ="target_details">
	<br/>
	<br/>
<table>
	<tr>
<td><p id="link_for_creating_new_target"><%= link_to 'CREATE PERSONAL TARGET', new_target_path, class: 'btn btn-sm btn-outline-success' %></p></td>
<td><p id="link_for_creating_new_target"><%= link_to 'CREATE GROUP TARGET', groupnew_path, class: 'btn btn-sm btn-outline-warning' %></p></td>
<td><p id="link_for_creating_new_target"><%= link_to 'MY GROUP TARGETS', groupindex_path, class: 'btn btn-sm btn-outline-info' %></p></td>
</tr>
</table>
<br/>
<button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal">
  GROUP STALE TASKS
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel" style="color:black">GROUP STALE TASKS:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if @kk.present? %>
        <% @kk.each do |om, tm| %>
        <% s = Target.find(om) %>
        <div class="alert alert-danger" role="alert" id ="stale_task_alert">
                   
                   <b>TARGET NAME :</b><%= s.name %>
                   <br/>
                   <b>TASK NAME :</b><%= tm %>
                   <hr>
                   <b>ACCESS LINK :</b><a href="<%= target_path(s) %>">Click Here</a>
                   </div>
                  <br/>
<%end%>
<%else%>
<p>NO DATA TO DISPLAY.</p>
<%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<br/>
<br/>
<br/>
<hr id = "target_type_heading">
<h4><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="green" class="bi bi-easel-fill" viewBox="0 1 18 16">
  <path d="M8.473.337a.5.5 0 0 0-.946 0L6.954 2H2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h1.85l-1.323 3.837a.5.5 0 1 0 .946.326L4.908 11H7.5v2.5a.5.5 0 0 0 1 0V11h2.592l1.435 4.163a.5.5 0 0 0 .946-.326L12.15 11H14a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H9.046L8.473.337z"/>
</svg> MY ACTIVE GROUP TARGETS</h4>
<hr id = "target_type_heading">
<br/>
<%if @group_targets.present? %>
<% @group_targets.each do |group_targett| %>
               
               <% flagset = 0 %>
               <% total = 0 %>
               <% $fl = 0 %>
               <% tasktotal = group_targett.tasks.count %>
                <% group_targett.tasks.each do |tttt| %>

                  <% if  tttt.owner == current_user.id %>

                  <% $fl = $fl + 1 %>

                  <%end%> 
                <%end%>
              <% group_targett.tasks.each do |ttttt| %>

               <% if  ttttt.owner == current_user.id %>

               <% flagset = flagset + 1 %>

               

              <% total = total + ttttt.progress %>

              <% if ((flagset*100) != total) %>

<table class="table table-hover" id ="t_group_table">
  <% if flagset == $fl %>
    <tr id="target_index_row" id = "t_table_r">
      <td id="target_g"><h4 style="color:black"><%= group_targett.name %></h4></td>
      <td id="target_options"><%= link_to 'Review/', group_targett %>
          <%= link_to 'Edit', edit_target_path(group_targett) %>
          <%if group_targett.lead == current_user.id %>
          <%= link_to '/Delete', group_targett, method: :delete, data: { confirm: 'Are you sure?'} %></td>
          <%end%>
          <%end%>
    </tr>
    <%end%>
    <%end%>
    <%end%>
    <%end%>
    <%end%>
</table>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<hr id = "target_type_heading">
<h4><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="green" class="bi bi-easel-fill" viewBox="0 1 18 16">
  <path d="M8.473.337a.5.5 0 0 0-.946 0L6.954 2H2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h1.85l-1.323 3.837a.5.5 0 1 0 .946.326L4.908 11H7.5v2.5a.5.5 0 0 0 1 0V11h2.592l1.435 4.163a.5.5 0 0 0 .946-.326L12.15 11H14a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H9.046L8.473.337z"/>
</svg> COMPLETED GROUP TARGETS</h4>
<hr id = "target_type_heading">
<br/>
<%if @groupp_targets.present? %>
<% @groupp_targets.each do |group_target| %>
               <% flagset = 0 %>
               <% total = 0 %>
               <% $fl = 0 %>
               <% tasktotal = group_target.tasks.count %>
                <% group_target.tasks.each do |ttt| %>

                  <% if  ttt.owner == current_user.id %>

                  <% $fl = $fl + 1 %>

                  <%end%> 
                <%end%>
              <% group_target.tasks.each do |tttt| %>

               <% if  tttt.owner == current_user.id %>

               <% flagset = flagset + 1 %>

               

              <% total = total + tttt.progress %>

              <% if ((flagset*100) == total) %>

<table class="table table-hover" id ="tt_group_table">
    <% if flagset == $fl %>
    <tr id="target_index_row" id = "t_table_r">
  
      <td id="target_gy"><span><h4 style="color:black"><%= group_target.name %> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="navy" class="bi bi-pin-fill" viewBox="0 0 16 16">
  <path d="M4.146.146A.5.5 0 0 1 4.5 0h7a.5.5 0 0 1 .5.5c0 .68-.342 1.174-.646 1.479-.126.125-.25.224-.354.298v4.431l.078.048c.203.127.476.314.751.555C12.36 7.775 13 8.527 13 9.5a.5.5 0 0 1-.5.5h-4v4.5c0 .276-.224 1.5-.5 1.5s-.5-1.224-.5-1.5V10h-4a.5.5 0 0 1-.5-.5c0-.973.64-1.725 1.17-2.189A5.921 5.921 0 0 1 5 6.708V2.277a2.77 2.77 0 0 1-.354-.298C4.342 1.674 4 1.179 4 .5a.5.5 0 0 1 .146-.354z"/>
</svg><%= ((flagset* 100)/tasktotal) %></h4></td>
      <%if group_target.lead == current_user.id %>
      <td id="target_options"><%= link_to 'Review/', group_target %>
          <%= link_to 'Edit', edit_target_path(group_target) %>
          <%= link_to '/Delete', group_target, method: :delete, data: { confirm: 'Are you sure?'} %></td>
          <%else%>
          <td id="target_options"><%= link_to 'Review', group_target %></td>
          <%end%>
          <%end%>
    </tr>
    <%end%>
    <%end%>
    <%end%>
    <%end%>
    <%end%>
</table>
<br/>
<br/>
<br/>
<br/>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/targets/groupnew.html.erb
<br/>
<br/>
<br/>
<div class="container" id="newgroup_target">
<u><h4><b>GROUP TARGET</b></h4></u>
<br/>
<div class="alert alert-danger" role="alert" id = "group_head">
<b>GENERAL:</b>
</div>
<br/>
<%= render 'groupform', target: @target %>

<br/>
<br/>
<br/>

<%= link_to 'BACK', targets_path, class: 'btn btn-outline-primary' %>
<%= link_to 'HOME', home_path, class: 'btn btn-outline-primary'%>
</div>

app/views/targets/groupshow.html.erb
<div class="container">
 <%= alerts %>
<p><b>GENERAL INFORMATION:</b></p>

<br/>

<table class= "table table-striped" >
	<tr>

  <td><strong>Target Name:</strong></td>
  <td><%= @target.name %></td>
</tr>

<td><strong>Target Type:</strong></td>
  <td><p>GROUP</p></td>
</tr>

<tr>
  <td><strong>Target Description:</strong></td>
  <td><%= @target.description %></td>
</tr>

<tr>
  <td><strong>Start Date:</strong></td>
  <td><%= @target.begin %></td>
</tr>

<tr>
  <td><strong>End Date:</strong></td>
  <td><%= @target.end %></td>
</tr>

    <% if @target.doc.present? %>

	<tr><td><strong>Document:</strong></td>
	<td><%= link_to("Access Attached Document", @target.doc.url) %></td></tr>

	<% else %>
	<tr><td><strong>Document:</strong></td>
    <td><b><p style="color:navy">NO RESOURCE ATTACHED</p></b></td></tr>
    <% end %>

    
</table>
<br/>
<hr>

<br/>
<br/>
<p><b>RELATED TASKS:</b></p>
<br/>
<center>
<table class="table table-hover" id ="target_detailed_info" border="1">
	<thead>
		<td id ="col1"><b>TASK NAME</b></td></b>
		<td id ="col2"><b>COMPLETION BY</b></td>
		<td id ="col3"><b>POINTS</b></td>
		<td id ="col3"><b>COMPLETION</b></td>
	
	</thead>
	
	<% @target.tasks.each do |t| %>


	<tbody>
		<td id ="col1"><%= t.name %></td>
		<td id ="col2"><%= t.dateofcompletion %></td>
		<td id ="col3"><%= t.point %></td>
		<td id ="col3"><%= t.progress %></td>
		
		
	</tbody>
	<% end %>
</table>
</center>
<br/>
<br/>
<br/>
<%= link_to 'EDIT', edit_target_path(@target), class: 'btn btn-outline-primary' %> 
<%= link_to 'BACK', targets_path, class: 'btn btn-outline-primary' %>
<%= link_to 'HOME', home_path, class: 'btn btn-outline-primary' %>

</div>

app/views/targets/index.html.erb
<div class="container"id ="target_details">
	<br/>
	<br/>
<table>
	<tr>
<td><p id="link_for_creating_new_target"><%= link_to 'CREATE PERSONAL TARGET', new_target_path, class: 'btn btn-sm btn-outline-success' %></p></td>
<td><p id="link_for_creating_new_target"><%= link_to 'CREATE GROUP TARGET', groupnew_path, class: 'btn btn-sm btn-outline-warning' %></p></td>
<td><p id="link_for_creating_new_target"><%= link_to 'MY GROUP TARGETS', groupindex_path, class: 'btn btn-sm btn-outline-info' %></p></td>
</tr>
</table>
<br/>
<button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal">
  PERSONAL STALE TASKS
</button>
<div class="modal fade .modal-dialog-scrollable" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel" style="color:black">PERSONAL STALE TASKS:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if @jj.present? %>
        <% @jj.each do |hm, nm| %>
        <% k = Target.find(hm) %>

            <div class="alert alert-danger" role="alert" id ="stale_task_alert">
                   
                   <b>TARGET NAME :</b><%= k.name %>
                   <br/>
                   <b>TASK NAME :</b><%= nm %>
                   <hr>
                   <b>ACCESS LINK :</b><a href="<%= target_path(k) %>">Click Here</a>
                   </div>
                  <br/>
<%end%>
<%else%>
<p>NO DATA TO DISPLAY.</p>
<%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<br/>
<hr id = "target_type_heading">
<h4><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="green" class="bi bi-easel-fill" viewBox="0 1 18 16">
  <path d="M8.473.337a.5.5 0 0 0-.946 0L6.954 2H2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h1.85l-1.323 3.837a.5.5 0 1 0 .946.326L4.908 11H7.5v2.5a.5.5 0 0 0 1 0V11h2.592l1.435 4.163a.5.5 0 0 0 .946-.326L12.15 11H14a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H9.046L8.473.337z"/>
</svg> MY ACTIVE PERSONAL TARGETS</h4>
<hr id = "target_type_heading">
<br/>
<%if @personal_targets.present? %>

<% @personal_targets.each do |personal_target| %>
<% if personal_target.lead.blank? %>
<% fff = personal_target.tasks.count %>

              <% ggg = personal_target.tasks.sum(:progress) %>

              <% if ((fff*100) != ggg) %>
<table class="table table-hover" id ="t_table">
    <tr id="target_index_row" id = "t_table_r">
      <td id="target_h"><h4 style="color:black"><%= personal_target.name %></h4></td>
      <td id="target_options"><%= link_to 'Review/', personal_target %>
          <%= link_to 'Edit/', edit_target_path(personal_target) %>
          <%= link_to 'Delete', personal_target, method: :delete, data: { confirm: 'Are you sure?'} %></td>
          
    </tr>
    <%end%>
    <%end%>
    <%end%>
    <%end%>
</table>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<hr id = "target_type_heading">
<h4><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="green" class="bi bi-easel-fill" viewBox="0 1 18 16">
  <path d="M8.473.337a.5.5 0 0 0-.946 0L6.954 2H2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h1.85l-1.323 3.837a.5.5 0 1 0 .946.326L4.908 11H7.5v2.5a.5.5 0 0 0 1 0V11h2.592l1.435 4.163a.5.5 0 0 0 .946-.326L12.15 11H14a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H9.046L8.473.337z"/>
</svg> COMPLETED PERSONAL TARGETS</h4>
<hr id = "target_type_heading">
<br/>
<p>
        
        <% @completed_targets.each do |personal_ttt| %>
              <% if personal_ttt.lead.blank? %> 
              <% ff = personal_ttt.tasks.count %>

              <% gg = personal_ttt.tasks.sum(:progress) %>

              <% if ((ff*100) == gg) %>
            

              <table class="table table-hover" id ="t_table_t">
    <tr id="target_index_row" id = "t_table_rr">
      <td id="target_hhh"><h4 style="color:black"><%= personal_ttt.name %></h4></td>
      <td id="target_options"><%= link_to 'Review', personal_ttt %></td>
          
    </tr>
</table>
             

              <%end%>

                 <%end%>
              
                
  

       <% end %>

</p>
<br/>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/targets/show.html.erb
<br/>
<br/>
<div class="container-fluid">
 <%= alerts %>
<p><b>GENERAL INFORMATION:</b></p>

<br/>

<table class= "table table-striped" >
	<tr>

  <td><strong>Target Type:</strong></td>
  <% if @target.lead.present? %>
  <td><p style="color:navy"><b>GROUP</b></p></td>
  <%else%>
   <td><p style="color:navy"><b>PERSONAL</b></p></td>
   <%end%>
</tr>
	<tr>

  <td><strong>Name:</strong></td>
  <td><%= @target.name %></td>
</tr>

<tr>
  <td><strong>Description:</strong></td>
  <td><%= @target.description %></td>
</tr>

<tr>
  <td><strong>Start Date:</strong></td>
  <td><%= @target.begin.strftime("%d-%b-%Y") %></td>
</tr>

<tr>
  <td><strong>End Date:</strong></td>
  <td><%= @target.end.strftime("%d-%b-%Y") %></td>
</tr>

    <% if @target.doc.present? %>

	<tr><td><strong>Document:</strong></td>
	<td><%= link_to("Access Attached Document", @target.doc.url) %></td></tr>

	<% else %>
	<tr><td><strong>Document:</strong></td>
    <td><b><p style="color:navy">NO RESOURCE ATTACHED</p></b></td></tr>
    <% end %>

    
</table>
<br/>
<hr id = "group_target_hr">
<br/>

<% if @target.lead.present? %>
<p><b>GROUP MEMBERS</b></p>
<br/>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
  	<% @target.member.each do |mem|%>
  	<% p = mem.to_i %>
  	<% m = @target.lead.to_i %>
    <tr>
    	<% if User.find(p) == User.find(m) %>
      <td id = "lead_color"><%= User.find(p).name %></td>
      <%else%>
      <td id = "member_color"><%= User.find(p).name %></td>
      <%end%>
    </tr>
    <%end%>
    
   </tbody>
</table>
<br/>
<hr id = "group_target_hr">
<%end%>
<br/>
<p><b>RELATED TASKS:</b></p>
<br/>
<div class="alert alert-success" role="alert" id = "tar_show">TOTAL TASKS: <%= @target.tasks.count %></div>
<br/>
<div class="alert alert-info" role="alert" id = "tar_show">EARLY STAGES: <%= @v %></div>
<br/>
<div class="alert alert-success" role="alert" id = "tar_show">FINAL STAGES: <%= @n %></div>
<br/>
<div class="alert alert-info" role="alert" id = "tar_show">YET TO BE COMPLETED: <%= @x %>/<%= @g %></div>
<br/>
<br/>
<br/>
<center>
<table class="table table-hover" id ="target_detailed_info" border="1">
	<thead>
		<td id ="col1"><b>TASK NAME</b></td></b>
		<td id ="col99"><b>OWNED BY</b></td></b>
		<td id ="col2"><b>DEADLINE</b></td>
		<td id ="col3"><b>STATUS</b></td>
	
	</thead>
	
	<% @target.tasks.each do |t| %>
    <% j = t.owner.to_i %>

	<tbody>
		<td id ="col1"><% if t.point.between?(0,5)%>
    <svg width="1em" height="2em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="purple" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
        </svg>
    <% elsif t.point.between?(6,10)%>
    <svg width="1em" height="2em" viewBox="0 0 16 16" class="bi bi-chevron-double-up" fill="purple" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M7.646 2.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 3.707 2.354 9.354a.5.5 0 1 1-.708-.708l6-6z"/>
        <path fill-rule="evenodd" d="M7.646 6.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 7.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
        </svg>
    <%end %><%= t.name %></td>
		<td id ="col2"><%= User.find(j).name %></td>
		<td id ="col2"><%= t.dateofcompletion.strftime("%d-%m-%Y") %></td>
		
		<% if t.progress.between?(25,49)%>
		<td id ="col6"><%= t.progress %></td>
		<% elsif t.progress.between?(50,74)%>
		<td id ="col7"><%= t.progress %></td>
		<% elsif t.progress.between?(75,100) %>
		<td id ="col8"><%= t.progress %></td>
		<%else%>
		<td id ="col9"><%= t.progress %></td>
		<%end%>
	</tbody>
	<% end %>
</table>
<br/>
<hr id = "group_target_hr">
<br/>
</center>
<br/>
<br/>
<%= link_to 'EDIT', edit_target_path(@target), class: 'btn btn-outline-primary' %> 
<%= link_to 'BACK', targets_path, class: 'btn btn-outline-primary' %>
<%= link_to 'HOME', home_path, class: 'btn btn-outline-primary' %>

</div>