config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :itenaries
  resources :solutions
  resources :questions
  resources :quizzes
  resources :information
  resources :tours
  resources :estimates
  resources :researches
  resources :feedbacks
  devise_for :admins
  resources :words
  resources :communities
  resources :years
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { registrations: "registrations" }
  resources :stories
  resources :targets
  root "welcome#welcome" 
  
  get 'docipedias/', to: 'docipedias#index', as: 'index'

  resources :conversations do
   resources :messages
  end

  


  get 'home/' => 'home#home', as: 'home'
  get 'accountsettings/' => 'home#accountsettings', as: 'accountsettings'
  get 'systemaccess/' => 'home#systemaccess', as: 'systemaccess'
  get 'targetreport/' => 'home#targetreport', as: 'targetreport'
  get 'yearreport/' => 'home#yearreport', as: 'yearreport'
  get 'expensereport/' => 'home#expensereport', as: 'expense'
  get 'bookmark/' => 'home#bookmark', as: 'bookmark'
  get 'custom/' => 'home#custom', as: 'custom'
  get 'bucket_list/' => 'home#bucket_list', as: 'bucket_list'
  get 'set_bucket_list/' => 'home#set_bucket_list', as: 'set_bucket_list'
  get 'destinations' => 'home#destinations', as: 'destinations'
  get 'news' => 'home#news', as: 'news'
  resources :visits

  
 
  

  get 'groupnew/' => 'targets#groupnew', as: 'groupnew'
  get 'groupindex/' => 'targets#groupindex', as: 'groupindex'
  get 'othernew/' => 'itenaries#othernew', as: 'othernew'

   get 'launch/' => 'quizzes#launch', as: 'launch'
   get 'aroundme/' => 'topics#aroundme', as: 'aroundme'
   get 'technology/' => 'topics#technology', as: 'technology'
   get 'travel/' => 'topics#travel', as: 'travel'
   get 'food/' => 'topics#food', as: 'food'
   get 'career/' => 'topics#career', as: 'career'
   get 'examination/' => 'topics#examination', as: 'examination'

 

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
    class ConversationsController < ApplicationController
        
        #Layout
        layout :determine_layout

        #Before-filters
        before_action :authenticate_user!
    	  
        #Index action.
        def index 
          @conversations = current_user.mailbox.conversations.page(params[:page])
        end

        #Show Action
    	  def show
          @conversation = current_user.mailbox.conversations.find(params[:id])
        end

        #New Action
        def new
         @recipients = User.all - [current_user]
        end
        
        #Create Action. Works together with "New".
        def create
        	@recipient = User.find(params[:user_id])
        	receipt = current_user.send_message(@recipient, params[:body], params[:subject])
        end

        #Layout method
        def determine_layout

          case current_user.colour

             when "orange"
             "myhomefour"

             when "black"
             "myhomethree"

             when "green"
             "myhometwo"

             else
             "myhome"
          end
      end


    end #End of class.

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class = "container" id = "my_emails">
	<br/>
	<br/>
<h4><b>MY CONVERSATIONS</b></h4>
<br/>
<br/>

<% @conversations.each do |conversation| %>

	
      
    

	<p><b>Sent Date:</b> <%= conversation.created_at %>
	 
		<%= link_to conversation.subject, conversation_path(conversation), class: 'btn btn-secondary btn-block' %></p>

    
<% end %>
<br/>
<br/>
<br/>
<br/>
<%= paginate @conversations, :container => false %>
<br/>
<hr>
<br/>
<br/>
<br/>
<%= alerts %> 
<%= link_to "CREATE EMAIL", new_conversation_path, class: 'btn btn-outline-success btn-block'%>
<br/>
<br/>
<br/>
<%= link_to "HOME", home_path, class: 'btn btn-outline-primary' %>
</div>

app/views/conversations/new.html.erb
<div class = "container" id ="new_convo">
<h2> New Conversation </h2>
<br/>
<br/>
<%= alerts %> 
<br/>
<%= form_tag conversations_path, method: :post do %>

<div class = "row">

	<div class = "col-md-4">

	<div class = "form-group">
		<%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %>
	</div>
     <br/>
     <br/>
	<div class = "form-group">
		<%= text_field_tag :subject, nil,  placeholder: "Subject", class: "form-control" %>
	</div>
	<br/>
	<br/>
</div>
<div class = "col-md-8">

	<div class = "form-group">
		<%= text_area_tag :body, nil, placeholder: "Body", "cols" => 20, "rows" => 10, class: "form-control" %>
	</div>
</div>
</div>

<br/>
<br>
<hr>
<br/>
<center>
   
	<%= submit_tag("SEND EMAIL", class: "btn btn-success") %>
	<% end %>
</center>
<br/>
<br/>
<br/>
<%= link_to "BACK", conversations_path, class: 'btn btn-outline-primary' %>
<%= link_to "HOME", home_path, class: 'btn btn-outline-primary' %>
</div>

app/views/conversations/show.html.erb
<div class ="container" id ="detailed_convo">
<b><%= @conversation.subject %></b>
<br/>
<hr>
<br/>

<% @conversation.receipts_for(current_user).each do |receipt| %>
<div>

	<b><p><%= receipt.message.sender.name %></b> commented: </p>
	<br/>
	<br/>
	<div class="jumbotron jumbotron-fluid">
  <div class="container">
    
    <p><%= receipt.message.body %></p>
  </div>
</div>
	

</div>
<% end %>
<br/>
<br/>
<br/>
<hr>
<br/>
<%= form_tag conversation_messages_path(@conversation), method: :post do %>

<div class = "form-group">
		<%= text_area_tag :body, nil, placeholder: "Type your reply...", "cols" => 20, "rows" => 10, class: "form-control" %>
	</div>
<br/>
<br/>
<%= submit_tag("SEND REPLY", class: "btn btn-primary") %>
<%= alerts %> 
<% end %>
<br/>
<br/>
<br/>
<%= link_to "BACK", conversations_path, class: 'btn btn-outline-primary' %>
<%= link_to "HOME", home_path, class: 'btn btn-outline-primary' %>
</div>