config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :itenaries
  resources :solutions
  resources :questions
  resources :quizzes
  resources :information
  resources :tours
  resources :estimates
  resources :researches
  resources :feedbacks
  devise_for :admins
  resources :words
  resources :communities
  resources :years
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { registrations: "registrations" }
  resources :stories
  resources :targets
  root "welcome#welcome" 
  
  get 'docipedias/', to: 'docipedias#index', as: 'index'

  resources :conversations do
   resources :messages
  end

  


  get 'home/' => 'home#home', as: 'home'
  get 'accountsettings/' => 'home#accountsettings', as: 'accountsettings'
  get 'systemaccess/' => 'home#systemaccess', as: 'systemaccess'
  get 'targetreport/' => 'home#targetreport', as: 'targetreport'
  get 'yearreport/' => 'home#yearreport', as: 'yearreport'
  get 'expensereport/' => 'home#expensereport', as: 'expense'
  get 'bookmark/' => 'home#bookmark', as: 'bookmark'
  get 'custom/' => 'home#custom', as: 'custom'
  get 'bucket_list/' => 'home#bucket_list', as: 'bucket_list'
  get 'set_bucket_list/' => 'home#set_bucket_list', as: 'set_bucket_list'
  get 'destinations' => 'home#destinations', as: 'destinations'
  get 'news' => 'home#news', as: 'news'
  resources :visits

  
 
  

  get 'groupnew/' => 'targets#groupnew', as: 'groupnew'
  get 'groupindex/' => 'targets#groupindex', as: 'groupindex'
  get 'othernew/' => 'itenaries#othernew', as: 'othernew'

   get 'launch/' => 'quizzes#launch', as: 'launch'
   get 'aroundme/' => 'topics#aroundme', as: 'aroundme'
   get 'technology/' => 'topics#technology', as: 'technology'
   get 'travel/' => 'topics#travel', as: 'travel'
   get 'food/' => 'topics#food', as: 'food'
   get 'career/' => 'topics#career', as: 'career'
   get 'examination/' => 'topics#examination', as: 'examination'

 

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
  class HomeController < ApplicationController
      
      require 'json'
      require 'httparty'
      #Layout
      layout :determine_layout
      #Before-filters
      before_action :authenticate_user!
      #Petergate authentication-accesses
      access all: [:home, :accountsettings, :trips, :systemaccess, :custom, :expensereport, :targetreport, :bookmark, :news, :yearreport, :bucket_list, :set_bucket_list, :destinations]
    
      def news
        @word = Word.all.order("created_at DESC")
        @latest = Word.last
      end

      def bucket_list
        @bucket_list = Visit.where(user_id: current_user.id)
        user = current_user.id
        @u = User.find(user)  
      end

      def destinations
        @m =  Visit.find(params[:m]) 
        g = ENV.fetch('API_Key')

        @q = @m.country.upcase
        @response = HTTParty.get("https://maps.googleapis.com/maps/api/place/textsearch/json?input=#{@q}+tourist+destinations&language=en&key=#{g}")
        @http_party_json = JSON.parse(@response.body)

        @response_two = HTTParty.get("https://maps.googleapis.com/maps/api/place/textsearch/json?input=#{@q}+top+hotels+and+resorts&language=en&key=#{g}")
        @http_party_json_two = JSON.parse(@response_two.body)

        @response_three = HTTParty.get("https://maps.googleapis.com/maps/api/place/textsearch/json?input=#{@q}+restaurants&language=en&key=#{g}")
        @http_party_json_three = JSON.parse(@response_three.body)

        @response_four = HTTParty.get("https://maps.googleapis.com/maps/api/place/textsearch/json?input=#{@q}+airport&type=airport&language=en&key=#{g}")
        @http_party_json_four = JSON.parse(@response_four.body)
      end 

      def bookmark
        user = current_user.id
        @u = User.find(user)
      end

      def trips 
      @bucket_list = Visit.where(user_id: current_user.id)
        user = current_user.id
        @u = User.find(user)  
          @e = (Estimate.where(user_id: current_user.id)).page(params[:page]).per(10)
      end

      def set_bucket_list
        user = current_user.id
        @u = User.find(user)
      end 

      def accountsettings
        @user = current_user.id
      end

      def systemaccess
        user = current_user.id
        @u = User.find(user)
      end

      def custom
        user = current_user.id
        @u = User.find(user)
      end

      def bookmark
        user = current_user.id
        @u = User.find(user)
      end

      def home

        @bookmarks = Bookmark.where(user_id: current_user.id)
        @festival = Festival.first
        @itenaries = Itenary.all
        @estimates = Estimate.where(user_id: current_user.id).page(params[:page])
        @quizzes = Quiz.all

        @years = Year.all
    	  @word = Word.last
    	  @user_targets = Target.all

        @c = []
        @w = []
        @s = []
        @ff = []


    	  @user_targets.each do |target|

    	 	     target.tasks.each do |task|
           
                  q = Date.today
                  z = Time.now
                  mm = task.updated_at
                  r = task.dateofcompletion
             

                  if (@flag = ((r-q).to_i >= 1)) 

                          if (task.owner == current_user.id)
                    
                                  @s << task.target_id
                                  @w << task.name
                                  @ff = @s.zip(@w)
                                  @c = Kaminari.paginate_array(@ff).page(params[:page]).per(2)
                    
                          end
                  
                  end

              end

         end 
       
    
      end #End of Home method.



      def determine_layout

      case current_user.colour

      when "orange"
        "myhomefour"

      when "black"
        "myhomethree"

      when "green"
        "myhometwo"

      else
        "myhome"
        
      end
      end
    
  end  #End of Class.

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_bookmark_fields.html.erb
<div class="nested-fields">
          <div class="form-group">

             <div>
                <%= link_to_remove_association 'Remove Bookmark', f, class: 'btn btn-outline-danger btn-sm' %>
             </div>

             <br/>
               
             <div class="form-group">
              <%= f.text_field :bname, placeholder:"Add Bookmark link", class: 'form-control'%>
             </div>
              

             <div class="form-group">
               <%= f.text_area :dname, placeholder:"Bookmark to be displayed as...", class: 'form-control'%>
             </div>

      
             </div>
</div>

app/views/home/_visit_fields.html.erb
<div class="nested-fields">
          <div class="form-group">

             <div>
                  <%= link_to_remove_association 'Remove Location', f, class: 'btn btn-outline-danger btn-sm' %>
             </div>
<br/>
               
                     <div class="form-group">
                   <%= f.text_field :country, placeholder:"Add Location name...", class: 'form-control'%>
                </div>
              

            <div class="form-group">
                   <%= f.text_area :description, placeholder:"Add description...", class: 'form-control'%>
                </div>

                <div class="form-group">
                  <%= f.date_field :schedule, class: 'form-control' %>
                </div>


             <div class="form-group">
              <label class = 'btn btn-sm btn-outline-warning'>
                BACKGROUND IMAGE<%= f.file_field :img, style: 'display: none;' %>
              </label>

              </div>


    


  

             </div>
         </div>

app/views/home/accountsettings.html.erb
  <body>
    <br>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  
          <%= link_to "PROFILE", accountsettings_path %>
                  
                <hr id ="settings">
              </li>

             <% if logged_in?(:site_admin) %>
              <li class="nav-item">
                <%= link_to "SYSTEM ACCESS", systemaccess_path %>
                <hr id ="settings">
              </li>
              <%else%>
              <li class="nav-item">
    
                  SYSTEM ACCESS 
            
                <hr id ="settings">
              </li>
              <%end%>
              <li class="nav-item">
                <%= link_to "CUSTOM", custom_path %>
                <hr id ="settings">
              </li>  

                <li class="nav-item">
                <%= link_to "SET BUCKET LIST", set_bucket_list_path %>
                <hr id ="settings">
              </li>
               
               <li class="nav-item">
                <%= link_to "BOOKMARKS", bookmark_path %>
                <hr id ="settings">
              </li>
            
            </ul>
          </div>
        </nav>


        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2" style="color:maroon" >PROFILE</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
               
              </div>
            
            </div>

          </div>
          <table class= "table table-success table-info">
  
  <tbody>
    <tr>
      <td><b>Name:-</b></td>
      <% z = @user %>
      <% a = User.find(z) %>
      <td><%= a.name %></td>
     
    </tr>
    <tr>
      <td><b>Email:-</b></td>
      <td><%= a.email %></td>
     
    </tr>

    <tr>
      <td><b>Joined On:-</b></td>
      <td><%= a.created_at.strftime("%d-%b-%Y") %></td>
     
    </tr>

    <tr>
      <td><b>Last Updated:-</b></td>
      <td><%= a.updated_at.strftime("%d-%b-%Y") %></td>
     
    </tr>

     <tr>
      <td><b>Access:- </b></td>
      <% r = a.roles %>
      <td><%= r[0] %></td> 
    

     
    </tr>
    
    <tr>
      <td><b>Total Logins:-</b></td>
      <td><%= a.sign_in_count %></td>
     
    </tr>

    <tr>
      <td><b>Last Login On:-</b></td>
      <td><%= a.last_sign_in_at.strftime("%d-%b-%Y") %></td>
     
    </tr>

    <tr>
      <td><b>Journal Subscription:-</b></td>
      <% if a.subscribe == "YES" %>
      <td>YES</td>
      <%else%>
      <td>NO</td>
      <%end%>
     
    </tr>

  </tbody>
</table>

          
        </main>
      </div>
    </div>

   
   
  </body>

app/views/home/bookmark.html.erb
  <body>
    <br>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  
              <%= link_to "PROFILE", accountsettings_path %>
                  
                <hr id ="settings">
              </li>

             <% if logged_in?(:site_admin) %>
              <li class="nav-item">
                <%= link_to "SYSTEM ACCESS", systemaccess_path %>
                <hr id ="settings">
              </li>
              <%else%>
              <li class="nav-item">

                SYSTEM ACCESS
              
                <hr id ="settings">
              </li>
              <%end%>
              <li class="nav-item">
                <%= link_to "CUSTOM", custom_path %>
                <hr id ="settings">
              </li>
              
              <li class="nav-item">
                <%= link_to "SET BUCKET LIST", set_bucket_list_path %>
                <hr id ="settings">
              </li>

                <li class="nav-item">
                <%= link_to "BOOKMARKS", bookmark_path %>
                <hr id ="settings">
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2" style="color:maroon" >SET ACCOUNT BOOKMARKS</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
               
              </div>
            
            </div>

          </div>

          <div class="container" id = "arrangement">
            <h6><b>*Bookmarks will be displayed at Homepage.</b></h6>
  

               <%= form_for @u, url: registration_path(@u) do |f| %>
         
         <table>
         <br/>
<br/>
<br/>
<div>
  <%= link_to_add_association 'Add Bookmark', f, :bookmarks, class: 'btn btn-sm btn-outline-success' %>

 
</div>

 <div>
  <br/><b>Password to confirm:</b></td><td> <%= f.password_field :current_password %><br/>
<br/>
</div>
<br/>

<hr>



   </div>
         </div>

      </table>

          <br/>
          <br/>
          <hr id = "settt">
         <div class="actions">
    <%= f.submit "SAVE BOOKMARKS", class: 'btn btn-info btn-sm' %>
  </div>

         <%end%>
          
          
          
        </main>
      </div>
    </div>

   
   
  </body>

app/views/home/bucket_list.html.erb
  <div id = "bucket_list_main_img">
    

<div class="container" id = "headingcontainer">
<img src= "<%= @u.headingimg.url %>", alt="To set the image, navigate to Account Settings >> Custom." width="100%" height="auto">
<div class="bottom-left"><%= current_user.heading %></div>
 
</div>
  </div>
<br/>
  

    <div class=".container-fluid" id = "listcon">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        <% @bucket_list.each do |mylist| %>

     

        <div class="col">
          <div class="card shadow-sm">
      
             <% if mylist.img.present? %>
            <%= image_tag mylist.img.url %>
            <%end%>
         


            <div class="card-body">
             <center> <b> <i class="fa fa-globe" aria-hidden="true"></i> <%= mylist.country.upcase %></b>, 
              #<%= mylist.schedule.strftime("%d-%B-%Y") %></center>
              <br/>
              <p class="card-text"><i class="fa fa-info" aria-hidden="true"></i> <%= mylist.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                </div>
                <small class="text-muted"><B>ADDED:</B> <%= mylist.created_at.strftime("%d-%B-%y") %></small>
                


              </div>
          
            <hr>
<%= link_to "VIEW TOP DESTINATIONS", destinations_path(:m => mylist.id), class: "btn btn-sm btn-outline-info" %>
<%= link_to 'REMOVE', visit_url(mylist), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %>
        
  </div>
          </div>
       <br/>
        </div>

        <%end%>

      </div>

      
 
      <hr>

    </div>
 



   

app/views/home/custom.html.erb
  <body>
    <br>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  
              <%= link_to "PROFILE", accountsettings_path %>
                  
                <hr id ="settings">
              </li>

             <% if logged_in?(:site_admin) %>
              <li class="nav-item">
                <%= link_to "SYSTEM ACCESS", systemaccess_path %>
                <hr id ="settings">
              </li>
              <%else%>
              <li class="nav-item">

                SYSTEM ACCESS
              
                <hr id ="settings">
              </li>
              <%end%>
              <li class="nav-item">
                <%= link_to "CUSTOM", custom_path %>
                <hr id ="settings">
              </li>
              
              <li class="nav-item">
                <%= link_to "SET BUCKET LIST", set_bucket_list_path %>
                <hr id ="settings">
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2" style="color:maroon" >CUSTOM SETTINGS</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
               
              </div>
            
            </div>

          </div>

          <div class="container" id = "arrangement">
            <p><b>AVAILABLE COLOURS</b></p>
  <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
    <div class="col">
      <div class="p-3 border" id = "ob"><b>Ocean Blue</b></div>
    </div>
    <div class="col">
      <div class="p-3 border" id = "pg" ><b>Parrot Green</b></div>
    </div>
    <div class="col">
      <div class="p-3 border" id = "db"><b>Dense Black</b></div>
    </div>
    <div class="col">
      <div class="p-3 border" id = "so"><b>Sun Orange</b></div>
    </div>
  </div>
<hr id = "customm">

        <%= form_for @u, url: registration_path(@u) do |f| %>
         
         <table>
          <tr>
          <td><b>Select Colour:</b></td> <td><%= f.select :colour, '<option value="blue">Ocean Blue</option><option value="green">Parrot Green</option><option value="black">Dense Black</option><option value="orange">Sun Orange</option>'.html_safe %></td>
          </tr>
          <br/>
          <tr>
          <td><b>Set Application Name:</b></td><td> <%= f.text_field :branding %></td>
         </tr>
          <br/>
          <tr>
          <td><b>Bucket List Page:</b></td><td> <%= f.text_field :heading %></td>
        </tr>
            <br/>
            <tr>
          <td><b>Bucket List Image:</b></td><td> <%= f.file_field :headingimg %></td>
        </tr>
          <br/>
          <tr>
          <td><b>Password to confirm:</b></td><td> <%= f.password_field :current_password %></td>
        </tr>

      </table>

          <br/>
          <br/>
          <hr id = "settt">
         <div class="actions">
    <%= f.submit "UPDATE MY CREDENTIALS", class: 'btn btn-info btn-sm' %>
  </div>

         <%end%>
          
          
        </main>
      </div>
    </div>

   
   
  </body>

app/views/home/news.html.erb
<div class = ".container-fluid" id = "new_news_container">

<br/>
<br/>
<div class="alert alert-success" role="alert" id = "news_alert">
  <h4 class="alert-heading">MIRROR - New features and updates !</h4>

   <h6 id = "news_update_date"><b>LAST UPDATED: <%= @latest.updated_at.strftime("%d-%B-%Y") %></b></h6>

</div>

<br/>
<br/>
<br/>
<br/>

<% @word.each do |word| %>
<div class="vl" id = "nvl">
<p><b>RELEASE:</b> <%= word.wordtitle.upcase %></b></h4>

	 <h6 id = "news_update_date"><b>DATE: <%= word.created_at.strftime("%d-%B-%Y") %></b></h6>
</p>

<p>
  <%= markdown (word.meaning) %>
</p>
</div>
<br/>
<hr>
<%end%>
</div>

app/views/home/set_bucket_list.html.erb
  <body>
    <br>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  
              <%= link_to "PROFILE", accountsettings_path %>
                  
                <hr id ="settings">
              </li>

             <% if logged_in?(:site_admin) %>
              <li class="nav-item">
                <%= link_to "SYSTEM ACCESS", systemaccess_path %>
                <hr id ="settings">
              </li>
              <%else%>
              <li class="nav-item">

                SYSTEM ACCESS
              
                <hr id ="settings">
              </li>
              <%end%>
              <li class="nav-item">
                <%= link_to "CUSTOM", custom_path %>
                <hr id ="settings">
              </li>
              
              <li class="nav-item">
                <%= link_to "SET BUCKET LIST", set_bucket_list_path %>
                <hr id ="settings">
              </li>

                <li class="nav-item">
                <%= link_to "BOOKMARKS", bookmark_path %>
                <hr id ="settings">
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2" style="color:maroon" >SET YOUR BUCKET LIST</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
               
              </div>
            
            </div>

          </div>

          <div class="container" id = "arrangement">
          <h6><b>*Add city names to the list for more accurate results.</b></h6>



        <%= form_for @u, url: registration_path(@u) do |f| %>
         
         <table>
         <br/>
<br/>
<br/>
<div>
  <%= link_to_add_association 'Add Location', f, :visits, class: 'btn btn-sm btn-outline-success' %>

 
</div>

 <div>
  <br/><b>Password to confirm:</b></td><td> <%= f.password_field :current_password %><br/>
<br/>
</div>
<br/>

<hr>



   </div>
         </div>

      </table>

          <br/>
          <br/>
          <hr id = "settt">
         <div class="actions">
    <%= f.submit "ADD TO MY BUCKET LIST", class: 'btn btn-info btn-sm' %>
  </div>

         <%end%>
          
          
        </main>
      </div>
    </div>

   
   
  </body>

app/views/home/systemaccess.html.erb
  <body>
    <br>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  
              <%= link_to "PROFILE", accountsettings_path %>
                  
                <hr id ="settings">
              </li>

              <% if logged_in?(:site_admin) %>
              <li class="nav-item">
                <%= link_to "SYSTEM ACCESS", systemaccess_path, :disabled => true %>
                <hr id ="settings">
              </li>
              <%else%>
              <li class="nav-item">
                
                  SYSTEM ACCESS
          
                <hr id ="settings">
              </li>
              <%end%>
              <li class="nav-item">
                <%= link_to "CUSTOM", custom_path %>
                <hr id ="settings">
              </li>

                <li class="nav-item">
                <%= link_to "SET BUCKET LIST", set_bucket_list_path %>
                <hr id ="settings">
                </li>

                  <li class="nav-item">
                <%= link_to "BOOKMARKS", bookmark_path %>
                <hr id ="settings">
              </li>
             
            
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2" style="color:maroon" >SELECT ROLE</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
               
              </div>
            
            </div>

          </div>
          <h6><u>AVAILABLE ROLES</u></h6>
          <table border = "2">
            <tr>
              <td><b>User</b></td><td>The role provides the full access of the software except the administrartor controls. Also, a user cannot contribute to the KB articles, nor they can delete any story. </td>
            </tr>
             <tr>
              <td><b>Administrator</b></td><td>This role have the access to the administrator section in addition to the user access.</td>
            </tr>
          </table>
         <%= form_for @u, url: registration_path(@u) do |f| %>
         
         <table>
          <tr>
          <td><b>Add Role:</b></td> <td><%= f.text_field :roles %></td>
          </tr>
          <br/>
          <br/>
          <tr>
          <td><b>Password to confirm:</b></td><td> <%= f.text_field :current_password %></td>
        </tr>

      </table>

          <br/>
          <br/>
          <hr id = "settt">
         <div class="actions">
    <%= f.submit "UPDATE MY CREDENTIALS", class: 'btn btn-info btn-sm' %>
  </div>

         <%end%>
          
        </main>
      </div>
    </div>

   
   
  </body>