config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :itenaries
  resources :solutions
  resources :questions
  resources :quizzes
  resources :information
  resources :tours
  resources :estimates
  resources :researches
  resources :feedbacks
  devise_for :admins
  resources :words
  resources :communities
  resources :years
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { registrations: "registrations" }
  resources :stories
  resources :targets
  root "welcome#welcome" 
  
  get 'docipedias/', to: 'docipedias#index', as: 'index'

  resources :conversations do
   resources :messages
  end

  


  get 'home/' => 'home#home', as: 'home'
  get 'accountsettings/' => 'home#accountsettings', as: 'accountsettings'
  get 'systemaccess/' => 'home#systemaccess', as: 'systemaccess'
  get 'targetreport/' => 'home#targetreport', as: 'targetreport'
  get 'yearreport/' => 'home#yearreport', as: 'yearreport'
  get 'expensereport/' => 'home#expensereport', as: 'expense'
  get 'bookmark/' => 'home#bookmark', as: 'bookmark'
  get 'custom/' => 'home#custom', as: 'custom'
  get 'bucket_list/' => 'home#bucket_list', as: 'bucket_list'
  get 'set_bucket_list/' => 'home#set_bucket_list', as: 'set_bucket_list'
  get 'destinations' => 'home#destinations', as: 'destinations'
  get 'news' => 'home#news', as: 'news'
  resources :visits

  
 
  

  get 'groupnew/' => 'targets#groupnew', as: 'groupnew'
  get 'groupindex/' => 'targets#groupindex', as: 'groupindex'
  get 'othernew/' => 'itenaries#othernew', as: 'othernew'

   get 'launch/' => 'quizzes#launch', as: 'launch'
   get 'aroundme/' => 'topics#aroundme', as: 'aroundme'
   get 'technology/' => 'topics#technology', as: 'technology'
   get 'travel/' => 'topics#travel', as: 'travel'
   get 'food/' => 'topics#food', as: 'food'
   get 'career/' => 'topics#career', as: 'career'
   get 'examination/' => 'topics#examination', as: 'examination'

 

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
	belongs_to :topic
	belongs_to :user
	has_many :comments, dependent: :destroy
	is_impressionable :counter_cache => true

	validates_presence_of :title, :body, :topic_id
    
    mount_uploader :Attachment, DocumentUploader
    mount_uploader :Img, DocumentUploader
	#Custom scope
	def self.recent       

		order("created_at DESC")

	end
end

app/controllers/stories_controller.rb
  class StoriesController < ApplicationController
      layout :determine_layout
    before_action :authenticate_user!
    before_action :set_story, only: [:show, :edit, :update, :destroy]

    before_action :user_signed_in?
    # GET /stories
    # GET /stories.json
    def index
      @stories = (Story.where(access: "PUBLIC")).recent.page(params[:page])
      @PVT = (Story.where(user_id: current_user.id))
      @private_stories = (@PVT.where(access: "PRIVATE")).recent.page(params[:page])
      @tweets = SocialTool.twitter_search
      @topics = Topic.all
    end

    # GET /stories/1
    # GET /stories/1.json
    def show
      @story = Story.includes(:comments).find(params[:id])
      @comment = Comment.new
      impressionist(@story)
    end

    # GET /stories/new
    def new
      @story = Story.new
      @topics = Topic.all
    end

    # GET /stories/1/edit
    def edit
    end

    # POST /stories
    # POST /stories.json
    def create
      @story = Story.new(story_params.merge(user_id: current_user.id))

      respond_to do |format|
        if @story.save
          format.html { redirect_to @story, notice: 'Story was successfully created.' }
          format.json { render :show, status: :created, location: @story }
        else
          format.html { render :new }
          format.json { render json: @story.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /stories/1
    # PATCH/PUT /stories/1.json
    def update
      respond_to do |format|
        if @story.update(story_params)
          format.html { redirect_to @story, notice: 'Story was successfully updated.' }
          format.json { render :show, status: :ok, location: @story }
        else
          format.html { render :edit }
          format.json { render json: @story.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /stories/1
    # DELETE /stories/1.json
    def destroy
      @story.destroy
      respond_to do |format|
        format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_story
        @story = Story.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def story_params
        params.require(:story).permit( :title, :access, :body, :topic_id, :user_id, :Attachment )
      end
      def determine_layout

      case current_user.colour

      when "orange"
      "myhomefour"

      when "black"
      "myhomethree"

      when "green"
      "myhometwo"

      else
      "myhome"
    end
  end
  end

app/helpers/stories_helper.rb
module StoriesHelper
	def gravatar_helper user
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 30
	end

	def twitter_parser tweet
		
    regex = %r{
      \b
      (
        (?: [a-z][\w-]+:
         (?: /{1,3} | [a-z0-9%] ) |
          www\d{0,3}[.] |
          [a-z0-9.\-]+[.][a-z]{2,4}/
        )
        (?:
         [^\s()<>]+ | \(([^\s()<>]+|(\([^\s()<>]+\)))*\)
        )+
        (?:
          \(([^\s()<>]+|(\([^\s()<>]+\)))*\) |
          [^\s`!()\[\]{};:'".,<>?«»“”‘’]
        )
      )
    }ix

    tweet.gsub(regex) do |url|
      "<a href='#{url}' target='_blank'>#{url}</a>"
    end.html_safe
  end


  class CodeRayify < Redcarpet::Render::HTML
     def block_code(code, language)
       CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true )

    options = {
      fenced_code_blocks: true,
      no_infra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <% story.errors.full_messages.each do |error| %>
    <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
   <p><b>NAME:</b></p>
   <%= form.text_field :title, placeholder: 'Story title...', :size => 80, class: 'form-content' %>
  </div>
  


  <div class="form-group">
    <p><b>SELECT TOPIC:</b></p>
   <b><% form.label :topic_id %></b>
   <%= form.collection_select(:topic_id, Topic.all, :id, :category,

                          {
                            selected: @story.topic_id,
                                  
                          },
                          class: "form-group"
                          )%>
  </div>

  <div class="form-group">
    <p><b>ADD DESCRIPTION:</b></p>
    <%= form.text_area :body, placeholder: 'Add content...', rows: 10, cols: 90, class: 'form-content' %>
    
  </div>
  
  <p><b>UPLOAD IMAGES:</b></p>
  <b><h5 style="font-size:10px">(Details: Order-> Supporting image will be displayed at the bottom.)</h5></b>
  <br>
  <div class = "row" >
    <div class = "col-md-2">
  <div class="form-group">
  <label class = 'btn btn-sm btn-outline-warning'>
    MAIN IMAGE<%= form.file_field :Attachment, style: 'display: none;' %>
  </label>

  </div>
</div>
<div class = "col">
  <div class="form-group">
  <label class = 'btn btn-sm btn-outline-warning'>
    SUPPORTING IMAGE<%= form.file_field :Img, style: 'display: none;' %>
  </label>

  </div>
</div>
</div>

<div class="form-group">
 <p><b>ACCESS:</b></p>
 <b><h5 style="font-size:10px">(*To mark story as private, enter "PRIVATE" in Access.)</h5></b>
   <%= form.text_field :access, class: 'form-content' %>

  </div>

  <br/>
  <br/>
  <div class="actions">
     <%= form.submit 'PUBLISH STORY', class: 'btn btn-sm btn-block btn-primary' %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<h4 class="blog-post-title" style="color:purple"><%= story.title %></h4>
            <p id = "story_details" class="btn btn-outline-info btn-sm"><b>Posted:</b><%= distance_of_time_in_words(story.created_at, Time.now) %> ago</p>
            <p id = "story_details" class="btn btn-outline-info btn-sm"><b>Last Edited:</b><%= distance_of_time_in_words(story.updated_at, Time.now) %> ago</p>
            <p id = "story_details" class="btn btn-outline-info btn-sm"><b>Total Views:</b><%= story.impressionist_count %></p>
            <br/>
            <br/>
            <%= link_to 'READ STORY',  story, class: 'btn btn-outline-success btn-sm' %>
            <% if story.user_id == current_user.id %>
            <%= link_to 'UPDATE STORY',edit_story_path(story), class: 'btn btn-outline-warning btn-sm' %>
            <% end %>
            <hr>

app/views/stories/edit.html.erb
<br/>
<br/>
<div class = "container" id="editt_story_cont">

	<div class="alert alert-info" role="alert" id ="edit_story_alert">


<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="green" class="bi bi-pen" viewBox="0 0 16 16">
  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
</svg><b>UPDATE STORY : <%= @story.title.upcase%> <h5 style="font-size:10px">(Last Updated On: <%= @story.updated_at.strftime("%m-%B-%Y") %>)</h5></p></b>
</div>

<br/>
<hr>
<%= render 'form', story: @story %>
<br/>
<br/>
<br/>
<br/>

 
<%= link_to 'BACK', stories_path, class: 'btn btn-sm btn-outline-primary' %>
<%= link_to 'HOME', home_path, class: 'btn btn-sm btn-outline-primary' %>
</div>

app/views/stories/index.html.erb
<br/>
<br/>
    <div class="container" id = "list_of_stories">
      <%= alerts %> 
            <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
        <%= link_to "AROUND ME", aroundme_path %>
        <%= link_to "TECHNOLOGY", technology_path %>
        <%= link_to "TRAVEL", travel_path %>
        <%= link_to "FOOD", food_path %>
        <%= link_to "CAREER", career_path %>
        <%= link_to "EXAMINATION", examination_path %>
        
        </nav>
      </div>

      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-12 px-0">
          <center>
          <p class="lead my-3" id="story_home_quote">When I do something, its all about self discovery. I want to learn and discover my own limits - Larry Ellison</p></center>
        </div>
      </div>
      <br/>
      <br/>

    <main role="main" class="container" id = "data">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h3 class="pb-3 mb-4 font-bold">
        
            <h5> <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="navy" class="bi bi-arrow-right-square-fill" viewBox="0 0 16 16">
  <path d="M0 14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v12zm4.5-6.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5a.5.5 0 0 1 0-1z"/>
</svg>  <%= link_to 'New Story', new_story_path , class: 'btn btn-sm btn-outline-secondary' %></h5>
          
            
          <div class="blog-post">
            <div class="alert alert-primary" role="alert" id = "public_story_heading">
<h5 style="color:navy;"><b>PUBLIC STORIES</h5></b>
</div>
            <hr id= "aboutafterline" >
            <br/>
            <%= render @stories %>


              <br/>
          
            
            <%= paginate @stories, :container => false %>
         
<br/>
<br/>

           <div class="alert alert-primary" role="alert" id = "public_story_heading">
<h5 style="color:navy;"><b>MY STORIES</h5></b>
</div>
            <hr id= "aboutafterline" >
          <br/>
          <% @private_stories.each do |story| %>
          <h4 class="blog-post-title" style="color:purple"><%= story.title %></h4>
            <p id = "story_details" class="btn btn-outline-info btn-sm"><b>Posted:</b><%= distance_of_time_in_words(story.created_at, Time.now) %> ago</p>
            <p id = "story_details" class="btn btn-outline-info btn-sm"><b>Last Edited:</b><%= distance_of_time_in_words(story.updated_at, Time.now) %> ago</p>
            <p id = "story_details" class="btn btn-outline-info btn-sm"><b>Total Views:</b><%= story.impressionist_count %></p>
            <br/>
            <br/>
            <%= link_to 'READ STORY',  story, class: 'btn btn-outline-success btn-sm' %>
            <% if story.user_id == current_user.id %>
            <%= link_to 'UPDATE STORY',edit_story_path(story), class: 'btn btn-outline-warning btn-sm' %>
            <% end %>
            <hr>
             <%end%>

             <%= paginate @private_stories, :container => false %>
        <br/>
        <br/>
        <br/>
        <br/>
          </div><!-- /.blog-post -->
          

        </div><!-- /.blog-main -->
 
       
        <aside class="col-md-4 blog-sidebar">

          <div class="p-3 mb-3 bg-light" >
            <h4 class="font-bold">About</h4>
            <p class="mb-0" id="about_info">Mirror Stories can be used to facilitate group working, a number of commentators argue that blogs encourage reflective learning (Chen et al., 2005), they can be used as a diary to keep a record of achievement and of interesting material.</p>
          </div>
          <hr id="aboutafterline">
          
          <br/>
          
           <% @tweets.each do |tweet| %>
          <div class="card text-black border- mb-1" id ="tweet_card" style="max-width: 18rem;">

            <div class="card-header bg-success " id = "tweetcardinside"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-square-text-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.5a1 1 0 0 0-.8.4l-1.9 2.533a1 1 0 0 1-1.6 0L5.3 12.4a1 1 0 0 0-.8-.4H2a2 2 0 0 1-2-2V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/> 
            </svg> LATEST TWEETS...
            </div>
            <%= twitter_parser tweet %>
            <div class="card-body">
          
            </div>
            
          </div>
          <% end %>
          
        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->

</div>

app/views/stories/new.html.erb
<br/>
<br/>
<div class ="container" id = "story_con">
<h4 style="color:navy"> WRITE YOUR THOUGHTS!!!</h4>
<br/>

<%= render 'form', story: @story %>


<br/>
<br/>
<br/>

<%= link_to 'BACK', stories_path, class: 'btn btn-sm btn-outline-primary' %>
<%= link_to 'HOME', home_path, class: 'btn btn-sm btn-outline-primary' %>

</div>

app/views/stories/show.html.erb
<div class = "container" id = "detailed_story">
   <%= alerts %> 
    <br/>
    <br/>
    <div class="card" id="story_title_card">
  <div class="card-header" id  = "story_title_section">
    <% if(@story.access) == "PUBLIC" %>
    <b><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-check2" viewBox="0 0 16 16">
  <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>

</svg>STORY TITLE</b>
<% end %>
<% if(@story.access) == "PRIVATE" %>
    <b><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-check2-all" viewBox="0 0 16 16">
  <path d="M12.354 4.354a.5.5 0 0 0-.708-.708L5 10.293 1.854 7.146a.5.5 0 1 0-.708.708l3.5 3.5a.5.5 0 0 0 .708 0l7-7zm-4.208 7-.896-.897.707-.707.543.543 6.646-6.647a.5.5 0 0 1 .708.708l-7 7a.5.5 0 0 1-.708 0z"/>
  <path d="m5.354 7.146.896.897-.707.707-.897-.896a.5.5 0 1 1 .708-.708z"/>
</svg> STORY TITLE</b>
<% end %>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      
      <p> <%= @story.title %> </p>
      
    </blockquote>
  </div>
</div>
    
    <br/>
    <br/>
    <div class="card" id="story_title_card">
  <div class="card-header" id  = "story_title_section">
    <b>CONTENT</b> 
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <% if @story.Attachment.present? %>
      <div id = "imgg"><%= image_tag @story.Attachment.url %></div>
      <%end%>
      <br/>
      <% if @story.Img.present? %>
      <div id = "imgg"><%= image_tag @story.Img.url %></div>
      <%end%>
      <p></strong><%= markdown @story.body %></p>
      <% u = @story.user_id%>
      <%  y = User.find(u) %>
      <br/>
      <footer class="blockquote-footer">Written By: <cite title="Source Title"><%= y.name %></cite></footer>
    </blockquote>
  </div>
</div>
    <br/>
    <hr id ="story_hr">
    <p><%= social_share_button_tag(@story.title, :url => "http://mirrorselfdevelopmenttool.com", desc: @story.body)%><p>
    <br/>

    <!-- Start of comment form -->
    <%= render 'comments/comment_form' %>
    <!-- End of comment form -->


    <!-- Start of comments -->
    <div id = "comments" data-story-id="<%= @story.id %>">
      <%= render @story.comments %>
    </div>
    <!-- End of comments -->

    <br/>
    <br/>
    <br/>
    <br/>
    <br/>

    <%= link_to 'BACK', stories_path, class: 'btn btn-outline-primary' %>
    <%= link_to 'HOME', home_path, class: 'btn btn-outline-primary' %>
    

 </div>